# Generated by Django 4.1.12 on 2024-12-11 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_email', models.EmailField(max_length=254)),
                ('leader_phone', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('team_members', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='events.eventregistration')),
            ],
        ),
    ]
