# Generated by Django 5.0.2 on 2024-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='screenshot',
            field=models.ImageField(default='screenshots/default.png', upload_to='screenshots/'),
            preserve_default=False,
        ),
    ]
